#if defined(__ICCARM__)
#pragma diag_suppress=Pa050
#endif
/**** DO NOT EDIT -- generated by the Makefile ********************************/
#if defined(__ICCARM__)
#pragma diag_default=Pa050
#endif

#if !defined(__LONGLONG_H__)
#define __LONGLONG_H__

/* do we have/want to use a long long type? */
#define HAVE_64BIT_LONG_LONG	/* yes */

/*
 * NO64BIT_LONG_LONG undef HAVE_64BIT_LONG_LONG
 */
#if defined(NO64BIT_LONG_LONG)
#undef HAVE_64BIT_LONG_LONG
#endif /* NO64BIT_LONG_LONG */

#endif /* !__LONGLONG_H__ */
